const tags = {
  "Skin Care": 1,
  "Frangipani Monoi Body": 1,
  "Decollete & Neck Cream": 1,
  "Shine Control": 1,
  "Skincare Tools": 1,
  "Cleansing Brushes": 1,
  "Lotions & Creams": 2,
  "Lotion": 2,
  "Cream":2,
  "Creams": 2,
  "Anti Aging":3,
  "Anti-Aging":3,
  "Anti-Aging Hand Repair Treatment":3,
  "Face":4,
  "Bath & Body":5,
  "Body Mist & Hair Mist":5,
  "Bath & Body Accessories":5,
  "Hair":6,
  "Haitian Black Castor Oil - Mango":6,
  "Renewing Argan Oil Of Morocco Extra Strength Penetrating Oil Dry":6,
  "Calm Down Ingrown Hair":6,
  "Masks":7,
  "Mask":7,
  "Makeup":8,
  "Trifecta Metallica Lip":8,
  "Sets & Palettes":8,
  "Body Makeup":8,
  "Eye Makeup":9,
  "Color Correcting":9,
  "Eye Treatment":10,
  "Eyes":10,
  "Get Your Chic On Eyes": 10,
  "Eye Cream":10,
  "GinZing Trio to Cleanse":10,
  "Hyperlift Eye Instant Eye Fix For Bags":10,
  "Lips":11,
  "Nails":12,
  "Nail Art & Design":12,
  "Nail Gifts":12,
  "Fragrance":13,
  "Fragrance Gift Sets":13,
  "Fragrance Gifts":13,
  "Hydration": 14,
  "Hydrating": 14,
  "Hydrating Body Toning Mist": 14,
  "Serum": 15,
  "Superfacial Organic": 15,
  "Oils & Serums": 15,
  "Treatment & Serums": 15,
  "Shaving": 16,
  "Hair Removal":16,
  "Shower": 17,
  "Bath & Shower": 17,
  "Bath Towels & Shower Caps": 17,
  "Suncare":18,
  "After Sun Care":18,
  "Oral Care":19,
  "Men":20,
  "Big Ass Brick of Soap":20,
  "Supplement":21,
  "Supplements":21,
  "Beyoutiful Hair":21,
  "Accessories": 22,
  "Tools & Brushes": 22
}

const nestedTags = {
  // Skin Care
  "Lip Care":1, 
  "Facial Rollers":2, 
  "Microneedle Face":2, 
  "Cryo Skin Icing Roller for Face":2, 
  "Face Wash":3, 
  "Moisturizer":4, 
  "Moisturizers & Treatments":4, 
  "Tinted Moisturizer":4, 
  "Face Moisturizer":4, 
  "Cold Plasma Plus+ Face'":4, 
  "Face Base Vitamin E Day Cream - Natural":4, 
  "Night Cream":5, 
  "Multi-Active Night Cream":5, 
  "Cleanser":6, 
  "Cleansers":6, 
  "Cleansing Oils":6, 
  "Kakadu C Brightening Daily Cleanser":6, 
  "Cleansing Wipes":6, 
  "Brightening Cleansing Gel":6, 
  "Exfoliator":7, 
  "Exfoliators & Scrubs":7, 
  "Acne & Blemish":8, 
  "Acne & Blemish Treatments": 8, 
  'Clean Shot Niacinamide': 8,
  "Dry Skin":9, 
  "Combination Skin":10,
  "Oily Skin":11,
  "Korean Skin Care":12,
  "Toner":13,

  // Face
  "Facial Peels":14,
  "Face Mist":15,
  "Face Oil":16,
  "Face Serum":70,
  "Face Masks":17,
  "Revolution Skincare x Jake-Jamie Coconut":17,
  "Eye Masks":17,
  "Sheet Masks": 17,
  "Facial Spray": 18,
  "Travel Size Facial Spray with Aloe": 18,
  "Facial Spray With Aloe": 18,

  // Bath & Body
  "Body Scrubs & Exfoliants":19,
  "Body Lotions & Creams":20,
  "Lavender Moon Body":20,
  "Advanced Body Smoothing Pre-Treatment":20,
  "Body Lotions":20,
  "Body Moisturizers":20,
  "Body Oils":20,
  "Hand & Foot Care":21,
  "Hand & Foot Treatment":21,
  "Hand Cream & Foot Cream":21,
  "Hand Soap & Sanitizers":21,
  "Manicure & Pedicure":22,
  "Manicure & Pedicure Tools":22,
  "Deodorant":23,
  "Nails":24,
  "Aromatherapy":25,

  //Hair
  "Hair Removal":26,
  "Hair Loss":27,
  "Thinning":27,
  "Loss": 27,
  "Hair Thinning":27,
  "Hair Thinning & Hair Loss": 27,
  "PHYTONOVATHRIX Ultimate Thickening":28,
  "Hair Treatment":28,
  "Hair Makeup":28,
  "Balanced Beauty Gummy Vitamins for Strong Hair":28,
  "Curl Preserve Nourishing Keratin Conditioner For Curly":28,
  "Damage Control Replenishing Keratin Conditioner-For Dry":28,
  "Curl Preserve Scalp Nourishing Shampoo For Curly":28,
  "Damage Control Scalp Replenishing Shampoo-For Dry":28,
  " Hair":28,
  "Gloss & Shine":28,
  "Hairspray":28,
  "Curl Enhancing":28,
  "Hair Color":29,
  "Colour Off Hair Color Remover for Temporary":29,
  "Root Touch Up":29,
  "Natural Hair Color":29,
  "Color Care":29,
  "Hair Styling": 30,
  "Styling":30,
  "Styling Products":30,

  //Makeup
  "Foundation":31,
  "Bronzer":32,
  "Concealer":33,
  "Blush":34,
  "Contouring":35,
  "Face Powder":36,
  "Setting Spray & Powder":36,
  "Face Primer": 37,
  "Everything Primer": 37,
  "Highlighter":38,
  "Makeup Remover":39,
  "Eye Makeup Remover":39,
  "Take The Day Off Makeup Remover For Lids":39,

  //Eye Makeup
  "Eyebrows":40,
  "Microwavable Eyebrow":40,
  "BrowFood Nourish At Night":40,
  "BrowFood Phyto-Medic":40,
  "Eyelashes": 41,
  "Brow & Lash Tools":41,
  "Phyto-Medic": 41,
  "Lash Primer & Serums":41,
  "Lash Couture Faux Mink":41,
  "Lash Couture Faux Mink Sequin": 41,
  'Ever EZ Lash Adhesive': 41,
  'Ever EZ Lashes #01': 41,
  'Ever EZ Lashes #03': 41,
  'Ever EZ Lashes #09': 41,
  'Ever EZ Lashes #11': 41,
  'Lash Couture 5th Ave': 41,
  'Lash Couture Adhesive': 41,
  'Lash Couture Faux Lash Extensions': 41,
  'Lash Couture Lash Adhesive': 41,
  'Lash Couture Naked Drama': 41,
  'Lash Couture Triple Push-Up': 41,
  'Looks So Natural Lash Flirty': 41,
  'Looks So Natural Lash Shy': 41,
  'Looks So Natural Lash': 41,
  ' Lash': 41,
  'Strip Lash Adhesive with Aloe': 41,
  'True Volume Lash': 41,
  "Eyeliner":42,
  "Super Pomade Vegan Eyeliner":42,
  "Eyeshadow":43,
  "Eyeshadow Palettes":43,
  "Tartelette Give":43,
  "Makeup Palettes":43,
  "Eye Primer & Base":43,
  "Mascara":44,

  // Eye Treatment
  "Eye Masks":45,
  "Retinol":46,
  "Eye Serums":47,

  // Lips
  "Lip Gloss":48,
  "Lip Care": 49,
  "Lip Plumpers": 49,
  "Lip Liner": 49,
  "Lip Tints & Balms": 49,
  "GrandeLIPS Hydrating Lip Plumper": 49,
  "Lip Stain": 49,
  "Lipstick":50,

  // Nails
  "Removers":51,
  "Nail Treatment":52,
  "Nail Treatments":52,
  "Nail Care": 52,
  "Cuticle Care": 52,
  "Nail Polish":53,
  "Gel Nail Polish":53,
  'fall nail polish':53,
  'Nail Lacquer Nail Polish':53,
  'Infinite Shine Long-Wear Nail Polish':53,
  'Gel Couture Nail Polish':53,
  "Nail Polish Stickers":53,
  "Top & Base Coats":54,
  "Start To Finish Base Coat":54,


  // Fragrance
  "Men's Fragrance":55,
  "Cologne":55,
  "Cologne Gift Sets":55,
  "Women's Fragrance":56,
  "Perfume Gift Sets":56,
  "Rollerballs & Purse Sprays":56,
  "Perfume":56,
  "Cologne":57,
  "Perfume":58,

  // Serums
  "Eye Serums":59,

  //Shower
  "Shampoo & Conditioner":60,
  "Amazing Grace Magnolia Shampoo":60,
  "Amazing Grace Perfumed Shampoo":60,
  "Raspberry Sorbet Shampoo":60,
  "Senorita Margarita Shampoo":60,
  "Melon Daiquiri Shampoo":60,
  "Fresh Cream Shampoo":60,
  "Hula Girl Shampoo":60,
  "Coconut Splash Shampoo":60,
  "Cleansing Conditioner": 60,
  "Scalp Recovery Conditioner": 60,
  " Moisturizing Conditioner for Itchy": 60,
  "Scalp Recovery Cleanser": 60,
  " Medicating Shampoo For Itchy": 60,
  "Intensive Therapy Hair Booster": 60,
  "Sensitive Baby Fragrance Free Shampoo & Wash For Sensitive & Eczema-Prone Skin": 60,
  "Travel Size 3-in-1 Tea Tree Shampoo":60,
  "3-In-1 Shampoo":60,
  "Travel Size 3-In-1 Shampoo":60,
  "3-in-1 Tea Tree Shampoo":60,
  "Conditioner":60,
  "Spiced Vanilla Shampoo":60,
  "Shampoo":60,
  "Dry Shampoo":60,
  "Shower Gel & Body Wash": 61,
  "Bubble Bath & Soaks": 61,
  "Calming Bubble Bath": 61,
  "Bath Bombs": 61,

  //Suncare
  "Self-Tanning":62,
  "Self Tanning":62,
  "Self-Tanning & Bronzing":62,
  "Sunscreen":63,

  // Men
  "Beard":64,
  "Beard Care": 64,
  "Scalp & Hair Leave-In Treatment System 2 (Fine/Progressed Thinning":64,
  "Men's Shaving": 65,
  "Aftershave": 65,
  "Shaving Cream & Razors":65,
  "SEB MAN The Multitasker Hair": 66,
  "Wax & Pomade":66,

  // Accessories
  "Tools & Brushes":67,
  "Tool & Brush Gifts":67,
  "Bath Sponges & Brushes":67,
  "Hair Styling Tools":67,
  "Hair Removal Tools":67,
  "Makeup Accessories": 68,
  "Makeup Brushes": 68,
  'Makeup Brushes & Tools': 68,
  'Makeup Bags & Cases': 68,
  'Brush Sets': 68,
}

export {
  nestedTags, tags
}